# Generated by Django 3.1.4 on 2021-07-21 06:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cashBalance', models.FloatField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=255)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=255)),
                ('cashBalance', models.FloatField()),
                ('menu', models.ManyToManyField(blank=True, related_name='available_in', to='glints.Menu')),
                ('openingHours', models.ManyToManyField(blank=True, to='glints.OpeningTime')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(default=uuid.uuid4, max_length=30, unique=True)),
                ('dishName', models.CharField(max_length=255)),
                ('restaurantName', models.CharField(max_length=255)),
                ('transactionAmount', models.FloatField()),
                ('transactionDate', models.DateTimeField(default=datetime.datetime(2021, 7, 21, 6, 26, 0, 292269))),
                ('menu_bought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glints.menu')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseHistory', to='glints.buyer')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glints.restaurant')),
            ],
        ),
    ]
