# Generated by Django 3.1.4 on 2021-07-21 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='dishName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='restaurantName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transactionAmount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 21, 7, 5, 7, 471427)),
        ),
    ]
