# Generated by Django 3.1.4 on 2021-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='available_in', to='glints.Menu'),
        ),
    ]
