# Generated by Django 3.1.4 on 2021-07-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0002_auto_20210719_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dish_name',
            new_name='dishName',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='prize',
            new_name='price',
        ),
    ]
