# Generated by Django 3.1.4 on 2021-07-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0003_auto_20210719_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='cash_balance',
            new_name='cashBalance',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='opening_hours',
            new_name='openingHours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='restaurantName',
        ),
    ]
