# Generated by Django 3.1.4 on 2021-07-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0006_auto_20210720_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cashBalance', models.FloatField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(default='82046ba6-bb73-4b4c-862c-b2f18b915776', max_length=30)),
                ('dishName', models.CharField(max_length=255)),
                ('restaurantName', models.CharField(max_length=255)),
                ('transactionAmount', models.FloatField()),
                ('transactionDate', models.DateTimeField()),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseHistory', to='glints.buyer')),
            ],
        ),
    ]
