# Generated by Django 3.1.4 on 2021-07-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0007_buyer_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default='e170f00b-8f62-4be9-b7fc-ddff0b272ad4', max_length=30),
        ),
    ]
