# Generated by Django 3.1.4 on 2021-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0008_auto_20210720_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default='15bcf14b-7e93-4b43-873c-bdf001e398e1', max_length=30),
        ),
    ]
