# Generated by Django 3.1.4 on 2021-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0009_auto_20210720_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default='9634d4b9-e2d2-423b-a397-bb22d5e6cf26', max_length=30),
        ),
    ]
