# Generated by Django 3.1.4 on 2021-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0010_auto_20210720_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default='04409356-2d91-4e60-b7fd-9b3828555e97', max_length=30),
        ),
    ]
