# Generated by Django 3.1.4 on 2021-07-20 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('glints', '0013_auto_20210720_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
    ]
